version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    restart: unless-stopped

  web:
    build: ./code_review_backend
    container_name: code_review_web
    ports:
      - '8000:8000'
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  worker:
    build: ./code_review_backend
    container_name: code_review_worker
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped
    command: python -m celery -A celery_app worker --loglevel=info